// auth actions
export const SET_ERRORS = "SET_ERRORS";
export const SET_MESSAGE = "SET_SETMESSAGE";
export const TOGGLE_USER_LOADING = "TOGGLE_USER_LOADING";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const SET_EXERCISES_META = "SET_EXERCISES_META";
export const SET_IS_EXERCISES_META_LOADED = "SET_IS_EXERCISES_META_LOADED";
export const SET_CATEGORY = "SET_CATEGORY";
export const SET_SUB_CATEGORY = "SET_SUB_CATEGORY";
export const SET_EXERCISE_SECTION = "SET_EXERCISE_SECTION";